from django.db import models
from django.utils.translation import gettext_lazy as _

PREFER_NOT_TO_SAY = 'Prefer not to say'
OTHER = 'Other'


class Gender(models.TextChoices):
    MALE = 'Male'
    FEMALE = 'Female'
    PREFER_NOT_TO_SAY = PREFER_NOT_TO_SAY
    OTHER = OTHER


class Zodiac(models.TextChoices):
    ARIES = 'Aries'
    TAURUS = 'Taurus'
    GEMINI = 'Gemini'
    CANCER = 'Cancer'
    LEO = 'Leo'
    VIRGO = 'Virgo'
    LIBRA = 'Libra'
    SCORPIO = 'Scorpio'
    SAGITTARIUS = 'Sagittarius'
    AQUARIUS = 'Aquarius'
    PISCES = 'Pisces'
    PREFER_NOT_TO_SAY = PREFER_NOT_TO_SAY


class EducationLevel(models.TextChoices):
    HIGH_SCHOOL = 'High School'
    BACHELORS = 'Bachelors'
    IN_COLLEGE = 'In College'
    MASTERS = 'Masters'
    IN_GRAD_SCHOOL = 'In Grad School'
    PHD = 'PhD'
    PREFER_NOT_TO_SAY = PREFER_NOT_TO_SAY


class MaritalStatus(models.TextChoices):
    SINGLE = 'Single'
    MARRIED = 'Married'
    SEPARATED = 'Seperated'
    DIVORCED = 'Divorced'
    WIDOWED = 'Widowed'
    PREFER_NOT_TO_SAY = PREFER_NOT_TO_SAY


class Smoke(models.TextChoices):
    NEVER_SMOKE = 'Never Smoke'
    SOCIALLY_SMOKE = 'Socially Smoke'
    SMOKE_REGULARLY = 'Smoke Regularly'
    TRYING_TO_QUIT = 'Trying to Quit'
    PREFER_NOT_TO_SAY = PREFER_NOT_TO_SAY


class Country(models.TextChoices):
    IRELAND = 'IRELAND', _('IRELAND')
    TURKEY = 'TURKEY', _('TURKEY')
    UNITED_STATES = 'UNITED STATES', _('UNITED STATES')
    SPAIN = 'SPAIN', _('SPAIN')
    GERMANY = 'GERMANY', _('GERMANY')
    ARGENTINA = 'ARGENTINA', _('ARGENTINA')
    AUSTRIA = 'AUSTRIA', _('AUSTRIA')
    AUSTRALIA = 'AUSTRALIA', _('AUSTRALIA')
    BELGIUM = 'BELGIUM', _('BELGIUM')
    CANADA = 'CANADA', _('CANADA')
    CHINA = 'CHINA', _('CHINA')
    FINLAND = 'FINLAND', _('FINLAND')
    FRANCE = 'FRANCE', _('FRANCE')
    GREECE = 'GREECE', _('GREECE')
    INDIA = 'INDIA', _('INDIA')
    ITALY = 'ITALY', _('ITALY')
    JAPAN = 'JAPAN', _('JAPAN')
    MEXICO = 'MEXICO', _('MEXICO')
    NETHERLANDS = 'NETHERLANDS', _('NETHERLANDS')
    SWEDEN = 'SWEDEN', _('SWEDEN')
    NORWAY = 'NORWAY', _('NORWAY')
    UKRAINE = 'UKRAINE', _('UKRAINE')
    RUSSIA = 'RUSSIA', _('RUSSIA')
    UNITED_KINGDOM = 'UNITED KINGDOM', _('UNITED KINGDOM')
    BRAZIL = 'BRAZIL', _('BRAZIL')


class Religion(models.TextChoices):
    CHRISTIAN = 'Christian'
    CATHOLIC = 'Catholic'
    HINDU = 'Hindu'
    JEWISH = 'Jewish'
    MUSLIM = 'Muslim'
    ORTHODOX = 'Orthodox'
    BUDDHIST = 'Buddhist'
    SPIRITUAL = 'Spiritual'
    AGNOSTIC = 'Agnostic'
    ATHEIST = 'Atheist'
    PREFER_NOT_TO_SAY = PREFER_NOT_TO_SAY
    OTHER = OTHER


class Politics(models.TextChoices):
    LIBERAL = 'Liberal'
    MODERATE = 'Moderate'
    CONSERVATIVE = 'Conservative'
    APOLITICAL = 'Apolitical'
    PREFER_NOT_TO_SAY = PREFER_NOT_TO_SAY
    OTHER = OTHER

# ANDORRA = 'ANDORRA'
# UNITED_ARAB_EMIRATES = 'UNITED ARAB EMIRATES'
# AFGHANISTAN = 'AFGHANISTAN'
# ANTIGUA_AND_BARBUDA = 'ANTIGUA AND BARBUDA'
# ANGUILLA = 'ANGUILLA'
# ALBANIA
# ARMENIA
# NETHERLANDS ANTILLES
# ANGOLA
# ANTARCTICA
# AMERICAN SAMOA
# ARUBA
# AZERBAIJAN
# BOSNIA AND HERZEGOVINA
# BARBADOS
# BANGLADESH
# BURKINA FASO
# BULGARIA
# BAHRAIN
# BURUNDI
# BENIN
# BERMUDA
# BRUNEI
# BOLIVIA
#
# BAHAMAS
# BHUTAN
# BOUVET ISLAND
# BOTSWANA
# BELARUS
# BELIZE
#
# COCOS [KEELING] ISLANDS
# CONGO [DRC]
# CENTRAL AFRICAN REPUBLIC
# CONGO [REPUBLIC]
# SWITZERLAND
# CÔTE D'IVOIRE
# COOK ISLANDS
# CHILE
# CAMEROON
#
# COLOMBIA
# COSTA RICA
# CUBA
# CAPE VERDE
# CHRISTMAS ISLAND
# CYPRUS
# CZECH REPUBLIC
#
# DJIBOUTI
# DENMARK
# DOMINICA
# DOMINICAN REPUBLIC
# ALGERIA
# ECUADOR
# ESTONIA
# EGYPT
# WESTERN SAHARA
# ERITREA
# ETHIOPIA
#
# FIJI
# FALKLAND ISLANDS [ISLAS MALVINAS]
# MICRONESIA
# FAROE ISLANDS
#
# GABON
#
# GRENADA
# GEORGIA
# FRENCH GUIANA
# GUERNSEY
# GHANA
# GIBRALTAR
# GREENLAND
# GAMBIA
# GUINEA
# GUADELOUPE
# EQUATORIAL GUINEA
#
# SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS
# GUATEMALA
# GUAM
# GUINEA-BISSAU
# GUYANA
# GAZA STRIP
# HONG KONG
# HEARD ISLAND AND MCDONALD ISLANDS
# HONDURAS
# CROATIA
# HAITI
# HUNGARY
# INDONESIA
#
# ISRAEL
# ISLE OF MAN
#
# BRITISH INDIAN OCEAN TERRITORY
# IRAQ
# IRAN
# ICELAND
#
# JERSEY
# JAMAICA
# JORDAN
#
# KENYA
# KYRGYZSTAN
# CAMBODIA
# KIRIBATI
# COMOROS
# SAINT KITTS AND NEVIS
# NORTH KOREA
# SOUTH KOREA
# KUWAIT
# CAYMAN ISLANDS
# KAZAKHSTAN
# LAOS
# LEBANON
# SAINT LUCIA
# LIECHTENSTEIN
# SRI LANKA
# LIBERIA
# LESOTHO
# LITHUANIA
# LUXEMBOURG
# LATVIA
# LIBYA
# MOROCCO
# MONACO
# MOLDOVA
# MONTENEGRO
# MADAGASCAR
# MARSHALL ISLANDS
# MACEDONIA [FYROM]
# MALI
# MYANMAR [BURMA]
# MONGOLIA
# MACAU
# NORTHERN MARIANA ISLANDS
# MARTINIQUE
# MAURITANIA
# MONTSERRAT
# MALTA
# MAURITIUS
# MALDIVES
# MALAWI
#
# MALAYSIA
# MOZAMBIQUE
# NAMIBIA
# NEW CALEDONIA
# NIGER
# NORFOLK ISLAND
# NIGERIA
# NICARAGUA
#
#
# NEPAL
# NAURU
# NIUE
# NEW ZEALAND
# OMAN
# PANAMA
# PERU
# FRENCH POLYNESIA
# PAPUA NEW GUINEA
# PHILIPPINES
# PAKISTAN
# POLAND
# SAINT PIERRE AND MIQUELON
# PITCAIRN ISLANDS
# PUERTO RICO
# PALESTINIAN TERRITORIES
# PORTUGAL
# PALAU
# PARAGUAY
# QATAR
# RÉUNION
# ROMANIA
# SERBIA
#
# RWANDA
# SAUDI ARABIA
# SOLOMON ISLANDS
# SEYCHELLES
# SUDAN
#
# SINGAPORE
# SAINT HELENA
# SLOVENIA
# SVALBARD AND JAN MAYEN
# SLOVAKIA
# SIERRA LEONE
# SAN MARINO
# SENEGAL
# SOMALIA
# SURINAME
# SÃO TOMÉ AND PRÍNCIPE
# EL SALVADOR
# SYRIA
# SWAZILAND
# TURKS AND CAICOS ISLANDS
# CHAD
# FRENCH SOUTHERN TERRITORIES
# TOGO
# THAILAND
# TAJIKISTAN
# TOKELAU
# TIMOR-LESTE
# TURKMENISTAN
# TUNISIA
# TONGA
# TRINIDAD AND TOBAGO
# TUVALU
# TAIWAN
# TANZANIA
#
# UGANDA
# U.S. MINOR OUTLYING ISLANDS
# URUGUAY
# UZBEKISTAN
# VATICAN CITY
# SAINT VINCENT AND THE GRENADINES
# VENEZUELA
# BRITISH VIRGIN ISLANDS
# U.S. VIRGIN ISLANDS
# VIETNAM
# VANUATU
# WALLIS AND FUTUNA
# SAMOA
# KOSOVO
# YEMEN
# MAYOTTE
# 'SOUTH_AFRICA'
# 'ZAMBIA'
