# Generated by Django 4.1.5 on 2023-01-08 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('Movie', 'Movie'), ('Tv Show', 'Tv Show'), ('Music', 'Music')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.genre'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.genre'),
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
        migrations.DeleteModel(
            name='MusicGenre',
        ),
    ]
