# Generated by Django 4.1.5 on 2023-01-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_actor_remove_sport_type_alter_genre_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
