# Generated by Django 4.1.5 on 2023-01-22 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.genre'),
        ),
    ]
