# Generated by Django 4.1.5 on 2023-01-22 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_tvshow_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cuisine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.cuisine'),
        ),
    ]
