# Generated by Django 4.1.5 on 2023-01-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_food_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
